import type { RenderTheme } from "@getpaseo/protocol/html-render";

export const STOCK_RENDER_THEMES: Record<"dark" | "light", RenderTheme> = {
  dark: {
    appearance: "dark",
    variables: {
      "--background": "#181B1A",
      "--foreground": "#fafafa",
      "--muted": "#272A29",
      "--muted-foreground": "#A1A5A4",
      "--card": "#1E2120",
      "--card-foreground": "#fafafa",
      "--popover": "#272A29",
      "--popover-foreground": "#fafafa",
      "--secondary": "#272A29",
      "--secondary-foreground": "#fafafa",
      "--border": "#252B2A",
      "--input": "#272A29",
      "--ring": "#d4d4d8",
      "--primary": "#fafafa",
      "--primary-foreground": "#181B1A",
      "--accent": "#20744A",
      "--accent-foreground": "#ffffff",
      "--accent-surface": "#272A29",
      "--accent-surface-foreground": "#fafafa",
      "--destructive": "#c64f43",
      "--destructive-foreground": "#ffffff",
      "--destructive-surface": "#272A29",
      "--warning": "#c09664",
      "--warning-foreground": "#fafafa",
      "--warning-surface": "#272A29",
      "--success": "#20744A",
      "--success-foreground": "#ffffff",
      "--info": "#3b82f6",
      "--info-foreground": "#fafafa",
      "--code-background": "#1E2120",
      "--code-foreground": "#fafafa",
      "--chart-1": "#20744A",
      "--chart-2": "#60a5fa",
      "--chart-3": "#fbbf24",
      "--chart-4": "#c084fc",
      "--chart-5": "#fb7185",
      "--chart-6": "#22d3ee",
      "--radius": "10px",
      "--font-sans":
        "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      "--font-mono":
        "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
      "--font-size-base": "14px",
    },
  },
  light: {
    appearance: "light",
    variables: {
      "--background": "#ffffff",
      "--foreground": "#1a1a1e",
      "--muted": "#f4f4f5",
      "--muted-foreground": "#71717a",
      "--card": "#fafafa",
      "--card-foreground": "#1a1a1e",
      "--popover": "#ffffff",
      "--popover-foreground": "#1a1a1e",
      "--secondary": "#f4f4f5",
      "--secondary-foreground": "#1a1a1e",
      "--border": "#e4e4e7",
      "--input": "#f4f4f5",
      "--ring": "#18181b",
      "--primary": "#18181b",
      "--primary-foreground": "#fafafa",
      "--accent": "#20744A",
      "--accent-foreground": "#ffffff",
      "--accent-surface": "#f4f4f5",
      "--accent-surface-foreground": "#1a1a1e",
      "--destructive": "#b04138",
      "--destructive-foreground": "#ffffff",
      "--destructive-surface": "#f4f4f5",
      "--warning": "#7b5d39",
      "--warning-foreground": "#1a1a1e",
      "--warning-surface": "#f4f4f5",
      "--success": "#20744A",
      "--success-foreground": "#ffffff",
      "--info": "#3b82f6",
      "--info-foreground": "#1a1a1e",
      "--code-background": "#fafafa",
      "--code-foreground": "#1a1a1e",
      "--chart-1": "#20744A",
      "--chart-2": "#2563eb",
      "--chart-3": "#d97706",
      "--chart-4": "#9333ea",
      "--chart-5": "#e11d48",
      "--chart-6": "#0891b2",
      "--radius": "10px",
      "--font-sans":
        "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
      "--font-mono":
        "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
      "--font-size-base": "14px",
    },
  },
};
